export const EVENTS  = {
    TEST: 'TEST',
    SEND_MESSAGE: 'SEND_MESSAGE',
    SEND_NAME: 'SEND_NAME',
    BROADCAST_NAME: 'BRODCAST_NAME',
    BROADCAST_MESSAGE: 'BRODCAST_MESSAGE',
    BROADCAST_USERS:'BROADCAST_USERS',
    DISCONNECT:'disconnect',
    BROADCAST_USER_LIST:'BROADCAST_USER_LIST',
    BROADCAST_SAVED_MESSAGE: 'BROADCAST_SAVED_MESSAGE',
    BROADCAST_USERS_RECENT:'BROADCAST_USERS_RECENT'

};

